version: '3'
services:
  notebook:
    container_name: python_notebook
    labels:
      description: Python 3.7 using Jupyter Notebooks
      name: jupyter notebook
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks:/usr/src/app/notebooks"
    environment:
      - "START_DIR=default-notebook"
    build:
      context: ./
      dockerfile: ./Dockerfile
